# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 23:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='state',
            field=models.CharField(default='todo', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 1, 23, 16, 5, 833529, tzinfo=utc)),
        ),
    ]
