# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(help_text="Doctor's name", max_length=60)),
                ('observations', models.TextField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="vaccine's name", max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='vaccines',
            field=models.ManyToManyField(blank=True, null=True, to='medical.Vaccines'),
        ),
    ]
