# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_auto_20170829_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinfo',
            name='vaccines',
            field=models.ManyToManyField(blank=True, to='medical.Vaccines'),
        ),
    ]
