# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
        ('pets', '0002_pets_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='medical_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.MedicalInfo'),
        ),
    ]
