# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionPersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Person's name", max_length=60)),
                ('surname', models.CharField(help_text="Person's surname", max_length=60)),
                ('birthday', models.DateField(help_text="Person's Birthday")),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', help_text="Person's sex", max_length=6)),
            ],
        ),
    ]
